---
- name: "Setting up Ubuntu Desktop"
  hosts: localhost
  connection: local
  become: true
  become_user: root
  roles:
    - desktop
    - role: gantsign.golang
      golang_version: 1.15.2
      golang_gopath: "{{ gopath }}"
    - role: andrewrothstein.terraform
      terraform_ver: 0.13.4
  vars:
    user: elliot
    gopath: $HOME/go-workspace
  pre_tasks:
    - name: Include secret variables from secrets.yaml
      include_vars:
        file: secrets.yaml
        name: secrets
      tags: user
