- name: "az: Download and add az-cli gpg key to apt-get keyring"
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: "az: Add az-cli repository to /etc/apt/sources.list"
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main"

- name: "az: Install az-cli"
  apt:
    pkg:
      - apt-transport-https
      - azure-cli
