- name: "general: Check if the current environment is WSL"
  shell: grep -qEi "(Microsoft|WSL)" /proc/version
  register: is_wsl

- name: "general: Add our /etc/wsl.conf"
  copy:
    src: wsl.conf
    dest: /etc/wsl.conf
  when: is_wsl.rc == 0

- name: "general: Install aptitude"
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: "general: Install general system packages"
  apt:
    pkg:
      - build-essential
      - dos2unix
      - vim

- name: "general: Set the default text editor"
  copy:
    src: default-editor.sh
    dest: /etc/profile.d/default-editor.sh
