- import_tasks: general.yaml
  tags: general
- import_tasks: docker.yaml
  tags: docker
- import_tasks: az_cli.yaml
  tags: azure
# - import_tasks: vscode.yaml
#   tags: vscode
# - import_tasks: terraform.yaml
#   tasks: terraform
# - import_tasks: golang.yaml
#   tags: golang
# - import_tasks: powershell.yaml
#   tags: powershell
# - import_tasks: node_version_manager.yaml
#   tasks: nvm
