- name: "pwsh: Download and add Powershell gpg key to apt-get keyring"
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"

- name: "pwsh: Add PowerShell repository to /etc/apt/sources.list"
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main"

- name: "pwsh: Install Powershell"
  apt:
    pkg: powershell
